function save(obj)

    if obj.stgsVisualizer.gif.save
        mystica.utils.saveGIF(...
            obj.stgsVisualizer.gif.name,...
            obj.figureFrames,...
            obj.stgsVisualizer.frameRate,...
            obj.stgsVisualizer.gif.compressionRatio)
    end
    if obj.stgsVisualizer.video.save
        mystica.utils.saveVIDEO(...
            obj.stgsVisualizer.video.name,...
            obj.figureFrames,...
            obj.stgsVisualizer.frameRate,...
            obj.stgsVisualizer.video.quality)
    end

end
